# Generated by Django 2.1 on 2018-08-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pesel_or_regon', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regon', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('policy_type', models.IntegerField(choices=[(1, 'komunikacja'), (2, 'mieszkanie'), (3, 'firma')], default=1)),
                ('date_issued', models.DateField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=7)),
                ('installments', models.IntegerField(choices=[(1, 'jedna'), (2, 'dwie'), (4, 'cztery')], default=1)),
                ('payment', models.IntegerField(choices=[(1, 'gotówka'), (2, 'przelew')], default=1)),
                ('isNNW', models.BooleanField(default=False)),
                ('isAssistance', models.BooleanField(default=False)),
                ('isCasco', models.BooleanField(default=False)),
                ('property', models.CharField(blank=True, max_length=200)),
                ('isTPL', models.BooleanField(default=False)),
                ('isBuilding', models.BooleanField(default=False)),
                ('isMovables', models.BooleanField(default=False)),
                ('isElectronics', models.BooleanField(default=False)),
                ('isAllRisk', models.BooleanField(default=False)),
                ('scan1', models.ImageField(blank=True, upload_to='')),
                ('scan2', models.ImageField(blank=True, upload_to='')),
                ('scan3', models.ImageField(blank=True, upload_to='')),
                ('scan4', models.ImageField(blank=True, upload_to='')),
                ('scan5', models.ImageField(blank=True, upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Client')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Insurer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Osobowy', 'Osobowy'), ('Ciężarowy', 'Ciężarowy'), ('Motocykl', 'Motocykl'), ('Przyczepa', 'Przyczepa'), ('Ciągnik Rolniczy', 'Ciągnik rolniczy'), ('Ciągnik Siodłowy', 'Ciągnik siodłowy'), ('Autobus', 'Autobus')], default='Osobowy', max_length=16)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('reg_number', models.CharField(max_length=10)),
                ('vin', models.CharField(max_length=17)),
                ('manufacture_year', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('power', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('first_registered', models.DateField()),
                ('leasing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Leasing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Client')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.Vehicle'),
        ),
    ]
