# Generated by Django 2.0.7 on 2018-08-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pesel_or_regon', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regon', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date_issued', models.DateField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=7)),
                ('installments', models.IntegerField(choices=[(1, 'jedna'), (2, 'dwie'), (4, 'cztery')], default=1)),
                ('payment', models.IntegerField(choices=[(1, 'gotówka'), (2, 'przelew')], default=1)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Insurer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('OS', 'Osobowy'), ('CI', 'Ciężarowy'), ('MO', 'Motocykl'), ('PR', 'Przyczepa'), ('CR', 'Ciągnik rolniczy'), ('CS', 'Ciągnik siodłowy'), ('AU', 'Autobus')], default='OS', max_length=2)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('reg_number', models.CharField(max_length=10)),
                ('vin', models.CharField(max_length=17)),
                ('leasing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.Leasing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.Client')),
            ],
        ),
    ]
