# Generated by Django 2.1 on 2018-09-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'pesel_or_regon')},
        ),
    ]
