# Generated by Django 2.0.7 on 2018-08-03 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_policy_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=1896),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_registered',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.IntegerField(default=1996),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power',
            field=models.IntegerField(default=66),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
