# Generated by Django 2.1 on 2018-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20180914_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.IntegerField(choices=[(1, 'komunikacja'), (2, 'mieszkanie'), (3, 'firma'), (4, 'podróżne'), (5, 'życie')], default=1),
        ),
    ]
