# Generated by Django 2.1 on 2018-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_auto_20180914_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
