# Generated by Django 2.1 on 2018-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20180914_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pesel_or_regon',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
    ]
