# Generated by Django 2.1 on 2018-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_auto_20180803_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='scan1',
            field=models.ImageField(blank=True, upload_to=models.CharField(max_length=20)),
        ),
        migrations.AddField(
            model_name='policy',
            name='scan2',
            field=models.ImageField(blank=True, upload_to=models.CharField(max_length=20)),
        ),
        migrations.AddField(
            model_name='policy',
            name='scan3',
            field=models.ImageField(blank=True, upload_to=models.CharField(max_length=20)),
        ),
    ]
