# Generated by Django 2.1 on 2018-09-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20180914_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gdpr',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
