# Generated by Django 2.1 on 2018-08-07 08:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_auto_20180806_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='scan1',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/samuel/projects/agenthelper/media'), upload_to='<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='scan2',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/samuel/projects/agenthelper/media'), upload_to='<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='scan3',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/samuel/projects/agenthelper/media'), upload_to='<django.db.models.fields.CharField>'),
        ),
    ]
