# Generated by Django 2.1 on 2018-08-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_auto_20180807_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='scan1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='policy',
            name='scan2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='policy',
            name='scan3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
