# Generated by Django 2.1 on 2018-08-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_auto_20180807_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='helper.Client'),
            preserve_default=False,
        ),
    ]
