# Generated by Django 2.1 on 2018-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_auto_20180808_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
