# Generated by Django 2.1 on 2018-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0011_auto_20180808_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default='b@b.pl', max_length=100),
            preserve_default=False,
        ),
    ]
