# Generated by Django 2.1 on 2018-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0012_auto_20180808_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='scan4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='scan5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
