# Generated by Django 2.1 on 2018-08-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0014_auto_20180824_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.IntegerField(choices=[(1, 'komunikacja'), (2, 'mieszkanie'), (3, 'firma')], default=1),
        ),
        migrations.AddField(
            model_name='policy',
            name='property',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='helper.Vehicle'),
        ),
    ]
