# Generated by Django 2.1 on 2018-08-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0015_auto_20180824_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.Vehicle'),
        ),
    ]
