# Generated by Django 2.1 on 2018-08-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0016_auto_20180824_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='isAllRisk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='isAssistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='isCasco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='isElectronics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='isNNW',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='isR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='isSE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='isTPL',
            field=models.BooleanField(default=False),
        ),
    ]
