# Generated by Django 2.1 on 2018-08-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0017_auto_20180824_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='isR',
            new_name='isBuilding',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='isSE',
            new_name='isMovables',
        ),
    ]
